version: '3.8'

services:
  web:
    build: .
    command: >
      bash -c "python manage.py collectstatic --noinput &&
               python manage.py makemigrations &&
               python manage.py migrate &&
               gunicorn --bind 0.0.0.0:8000 django_project.wsgi:application"
    volumes:
      - .:/home/app/web
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - ALLOWED_HOSTS=localhost 127.0.0.1
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    restart: always